### ISSUE TITLE
Midi export

### ISSUE THREAD

**Issue by dgrmunch** [alda-lang/alda-core#33] opened 2017-03-14 03:56 UTC
Is this feature in progress? It is the only thing I miss so far in this wonderful project :-)

**Comment by jgkamat** [comment] 2017-03-14 04:20
This is a dupe of #9

I don't know too much about the backend, but I don't think it would be too hard to implement, if there are libraries in the java midi api for this already. I do agree this is much needed (either this or MP3/wav export).

(if/when I get another large block of free time I _might_ be able to look at this, but I'm way too busy right now :cry:)

**Comment by daveyarwood** [comment] 2017-03-14 11:58
( @jgkamat I just had twins, so I know how you feel! 😵 )

Closing as duplicate of #9. So far, I don't believe anyone has started working on this feature, but contributions are always welcome!

**Closed as completed by daveyarwood** 2017-03-14 11:58 UTC

**Comment by dgrmunch** [comment] 2017-03-14 22:04
Congrats for the twins :-) 👍
