### ISSUE TITLE
[NOT AN ISSUE] But it would be great if it supports openjdk

### ISSUE THREAD

**Issue by dickensas** [alda-lang/alda-core#86] opened 2020-09-29 04:17 UTC
Check Java version

```
java -version
```

```
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```

C:\Program Files (x86)\Alda\alda.exe
```
This application requires a Java Runtime Environment 1.7.0
```

**Comment by daveyarwood** [comment] 2020-09-29 12:43
Hi @dickensas, I've seen this issue crop up a few times recently. I believe this is a duplicate of https://github.com/alda-lang/alda-client-java/issues/41.

See that issue for some suggestions about how to fix it. I would love to know if any of the suggestions work, so that maybe we can add some helpful information to the README for Windows users with OpenJDK.

**Closed as completed by daveyarwood** 2020-09-29 12:43 UTC
Labels: windows
