### ISSUE TITLE
bug when mixing length of notes (ms or s) and default no-length

### ISSUE THREAD

**Issue by damiendevienne** [alda-lang/alda-core#27] opened 2016-11-30 21:31 UTC
Hi ! Great tool, thanks! 
Maybe this is wanted, but it is suprising: when trying to use length of notes in seconds or millisecons I noticed that these lengths cannot be mixed with no-length (default) notes. For example
`d e` plays two notes (ok). 
`d2s e2s` plays both (2s each, ok). 
`d2s e` only plays the d (2 seconds...)
Any thoughts?

**Comment by daveyarwood** [comment] 2016-11-30 21:37
Nice catch - this is definitely a bug!

The intended behavior is for each "declared" note length (whether in seconds, milliseconds or standard notation like quarter notes) to be "sticky" and apply to every note following it as a "default" note length until there is another note with a declared note length.

**Comment by daveyarwood** [comment] 2016-12-05 13:16
Fixed in 0.1.2. Thanks again for reporting this! :)

**Closed as completed by daveyarwood** 2016-12-05 13:16 UTC
Labels: bug, low-hanging fruit
